---
title: "Supervised Penalized Canonical Correlation Analysis with the spCCA package"
package: spCCA
output:
  BiocStyle::html_document:
    includes:
      in_header: spcca.bioschemas.html
author:
- name: Andrea Thum
  email: andrea.thum@informatik.uni-halle.de
- name: Steffen Neumann
  email: sneumann@ipb-halle.de
abstract: |
  The supervised penalized canonical correlation approach (spCCA) is an 
   extension of the penalized CCA, where the experimental design is used 
   as a third data set (making the analysis supervised), and the correlation 
   of the biological data sets with the design data set is maximized to find 
   interpretable and meaningful canonical variables. This vignette shows 
   the spCCA analysis on a data set of Arabidopsis thaliana with gene expression 
   and metabolite intensity measurements, resulting in eight significant canonical
   variables. 
vignette: |
  %\VignetteIndexEntry{spCCA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: lit.bib
csl: biomed-central.csl
---

```{r LibraryPreload, echo=FALSE, results='hide'}
library(spCCA)
library(pcaMethods)
```

# Introduction

See [@Hotel36].

# Datasets

```{r}
X <- read.csv(system.file("arXiv.1405.1534", "MTBLS18.csv", package = "spCCA"))
Y <- read.csv(system.file("arXiv.1405.1534", "E-MTAB-3287.csv", package = "spCCA"))
Z <- read.csv(system.file("arXiv.1405.1534", "SAMEG179892.csv", package = "spCCA"))

pcX <- pca(X, nPcs=3, method="ppca")
X <- completeObs(pcX)

pcY <- pca(Y, nPcs=3, method="ppca")
Y <- completeObs(pcY)

```

# spCCA

```{r}
if(FALSE) {
  # Examples from simulated data, not working for arXiv data :-( )
  CCA3 <- getCCA3(X=X, Y=Y, Z=Z, numCV=3, max.counter.test=1, alpha=1)

  CCA3 <- getCCA3(X,Y,Z,numCV=2,  max.counter.test=1, n.r=1)
}

```





# References {.unnumbered}


# Session info

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
